<a href="https://colab.research.google.com/github/PsicoJazz/Ciencia-de-Dados/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importando a Bíblioteca**


In [ ]:
import numpy as np

# Criando lista aleatória

In [ ]:
dados = np.random.rand(2,3)

In [ ]:
dados

array([[0.24748552, 0.63553513, 0.14122808],
       [0.63703351, 0.74766987, 0.20539596]])

# Consultar tipo da variável

In [ ]:
dados.dtype

dtype('float64')

# Consultar dimentões e elementos

**Consultar dimentões e elementos**

In [ ]:
dados.ndim

2

In [ ]:
dados.shape

(2, 3)

# NDARRAY usando um array

**NDARRAY  usando um array**

In [ ]:
lista=[1,3,5,6.5,7.2]

In [ ]:
dados2 = np.array(lista)

In [ ]:
dados2

array([1. , 3. , 5. , 6.5, 7.2])

In [ ]:
lista2 = [[2,3,4,5,6],[1,2,3,6,7]]

In [ ]:
dados3 = np.array(lista2)

In [ ]:
dados3

array([[2, 3, 4, 5, 6],
       [1, 2, 3, 6, 7]])

**Outros arrays**

In [ ]:
dadoszero = np.zeros(10)

In [ ]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
dadoszero2 = np.zeros((2,3))

In [ ]:
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
dadosum = np.ones(5)

In [ ]:
dadosum

array([1., 1., 1., 1., 1.])

In [ ]:
dadosum2 = np.ones((2,3))

In [ ]:
dadosum2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
dadosseq = np.arange(10)

In [ ]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dadosseq2 = np.arange(10,20)

In [ ]:
dadosseq2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:

dadosseq3 = np.arange(0,20,2)

In [ ]:
dadosseq3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
dadosseq3.dtype

dtype('int64')

# Transformar tipo da variável

**Transformar tipo da variável**

In [ ]:
dadosseqflo = dadosseq3.astype(np.float64)

In [ ]:
dadosseqflo.dtype

dtype('float64')

# Aritméticas com array

**Aritméticas com array**

In [ ]:
dados4 = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
dados4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

As operações irá calcular os elementos na mesma posição

In [ ]:
dados4 * dados4

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [ ]:
dados4 - dados4

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
dados4 + dados4

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [ ]:
dados4 / dados4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
2/dados4

array([[2.        , 1.        , 0.66666667, 0.5       ],
       [0.4       , 0.33333333, 0.28571429, 0.25      ]])

Criar nova variavel e comparar

In [ ]:
dados5 = dados4 + dados4

In [ ]:
dados5

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [ ]:
dados4 >= dados5

array([[False, False, False, False],
       [False, False, False, False]])

# INDEXACAO

**INDEXACAO**

mostrar valor em um elemento

In [ ]:
dadosseq2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
dadosseq2 [5]

15

# Alteração de recortes dos dados, ND array broadcast

**Alteração de recortes dos dados, ND array broadcast**

mostra os dados em um intervalo especificado

In [ ]:
dadosseq [3:6]

array([3, 4, 5])

altera os dados nesse recorte da lista

In [ ]:
dadosseq [3:6]=20

In [ ]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

fatiar trecho dos dados

In [ ]:
fatiadados = dadosseq [2:8]

In [ ]:
fatiadados

array([ 2, 20, 20, 20,  6,  7])

quando alterado um dado numa fatia, altera no todo

In [ ]:
fatiadados [2]=250

In [ ]:
fatiadados

array([  2,  20, 250,  20,   6,   7])

uma fatia pode alterar todos seu elementos, alterando tambem o escopo

In [ ]:
fatiadados [:]=333

In [ ]:
dadosseq

array([  0,   1, 333, 333, 333, 333, 333, 333,   8,   9])

# Cópia da Dados

**Cópia da Dados**

In [ ]:
fatia2 = dadosseq [2:7].copy()

In [ ]:
fatia2

array([333, 333, 333, 333, 333])

In [ ]:
fatia2 [:]=100

In [ ]:
fatia2

array([100, 100, 100, 100, 100])

Como foi alterado uma cópia, nao altera o escopo original

In [ ]:
dadosseq

array([  0,   1, 333, 333, 333, 333, 333, 333,   8,   9])

# Array várias Dimensões

**Array várias Dimensões**

In [ ]:
dados6 = np.array([[1,2,3],[5,6,7],[8,9,10]])

In [ ]:
dados6

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Exibir elemento: [linha,coluna]

In [ ]:
dados6 [1,2]

7

# Mascara: comparações

**Mascara: comparações**

In [ ]:
dadosseq

array([  0,   1, 333, 333, 333, 333, 333, 333,   8,   9])

In [ ]:
mascara = (dadosseq < 10)

In [ ]:
mascara

array([ True,  True, False, False, False, False, False, False,  True,
        True])

Alterar todos os valores com base numa comparação

In [ ]:
comparacao = dadosseq [:].copy()

In [ ]:
comparacao

array([  0,   1, 333, 333, 333, 333, 333, 333,   8,   9])

In [ ]:
comparacao [comparacao < 10]=666

In [ ]:
comparacao

array([666, 666, 333, 333, 333, 333, 333, 333, 666, 666])

In [ ]:
dadosseq

array([  0,   1, 333, 333, 333, 333, 333, 333,   8,   9])

# Transposição: inverter matriz

**Transposição: inverter matriz**

In [ ]:
dados7 = np.arange(15).reshape ((3,5))

In [ ]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Comando DOT para multiplicação

**Comando DOT para multiplicação**

In [ ]:
np.dot(dados7.T , dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])